package com.bb_sz.auto.manager;


import com.bb_sz.auto.BuildConfig;

/**
 * Created by Administrator on 2017/3/17.
 */

public interface Contants {


    String VERSION = BuildConfig.VERSION_NAME;
    String LOGIN = "1";
    String LOGOUT = "2";

    String ANDROID = "android";
    String APP_FIRST_RUN = "SP_APP_FIRST_RUN";
    String KEY_RUN_TIMES = "KEY_RUN_TIMES";

    String SETTING_CHANGE_IP_KEY = "SETTING_CHANGE_IP_KEY";
    String SETTING_CHANGE_IP_COUNT_KEY = "SETTING_CHANGE_IP_COUNT_KEY";
    String SETTING_UNINSTALL_APP_KEY = "SETTING_UNINSTALL_APP_KEY";
    String SETTING_UNINSTALL_APP_KEYS_KEY = "SETTING_UNINSTALL_APP_KEYS_KEY";
    String SETTING_ONLY_IMEI_IMSI_KEY = "SETTING_ONLY_IMEI_IMSI_KEY";
    String SETTING_PHONE_REBOOT_KEY = "SETTING_PHONE_REBOOT_KEY";
    String SETTING_NOT_CHANGE_D_INFO_KEY = "SETTING_NOT_CHANGE_D_INFO_KEY";
    String SETTING_REBOOT_TIME_BLANK_KEY = "SETTING_REBOOT_TIME_BLANK_KEY";
    String SETTING_IS_RUN_NET_DATA_KEY = "SETTING_IS_RUN_NET_DATA_KEY";
    String SETTING_REBOOT_TIME_BLANK_NUMBER_KEY = "SETTING_REBOOT_TIME_BLANK_NUMBER_KEY";
    String SETTING_ON_CREATE_TIME_KEY = "SETTING_ON_CREATE_TIME_KEY";
    String KEY_RUN_FLAG = "KEY_RUN_FLAG";
    String KEY_RUN_ID = "KEY_RUN_ID";
    String PACKAGE_NAME = "com.bb_sz.auto";
    String KEY_INSTALL_TIME = "KEY_INSTALL_TIME";
    String SETTING_COUNT_START = "SETTING_COUNT_START";
    String KEY_PHONE_TYPE_SELECTED = "KEY_PHONE_TYPE_SELECTED";
    String BUGLY_ID = "f1ecea5cd0";
    String UPDATEUI = "UPDATEUI";
    String VPN_PASSWORD = "VPN_PASSWORD";
    String VPN_USER_NAME = "VPN_USER_NAME";
    String VPN_NAME = "VPN_NAME";
    String KEY_CUR_IP = "KEY_CUR_IP";
}
